- alias: Automatic Bar Lighting
  trigger:
  - platform: state
    entity_id: light.bar_bulb_1
    to: 'on'
  - platform: time
    minutes: '/1'
    seconds: 00
  action:
  - service: switch.bar_automatic_lighting_update

- alias: Low Battery Alert
  trigger:
    platform: numeric_state
    entity_id:
    - sensor.tradfri_motion_sensor
    below: 20
  action:
  - service: notify.rocketchat_status
    data_template:
      message: ":battery: {{ trigger.to_state.name }} is less than 20% battery"

- alias: Startup Notification
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: notify.rocketchat_status
    data:
      message: ":hass: Home Assistant is up and running"

- alias: Shutdown Notification
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: notify.rocketchat_status
    data:
      message: ":hass: Home Assistant is stopped"

