- platform: mqtt
  name: sonoff1905
  state_topic: "be3/bof/lamp01/stat/POWER"
  command_topic: "be3/bof/lamp01/cmnd/POWER"
  availability_topic: "be3/bof/lamp01/tele/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: sonoff7461
  state_topic: "be3/tux/lamp01/stat/POWER"
  command_topic: "be3/tux/lamp01/cmnd/POWER"
  availability_topic: "be3/tux/lamp01/tele/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: sonoff4126
  state_topic: "be3/tux/lamp02/stat/POWER"
  command_topic: "be3/tux/lamp02/cmnd/POWER"
  availability_topic: "be3/tux/lamp02/tele/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: sonoff1911
  state_topic: "be3/sys/lamp01/stat/POWER"
  command_topic: "be3/sys/lamp01/cmnd/POWER"
  availability_topic: "be3/sys/lamp01/tele/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: sonoff1645
  state_topic: "be3/tre/lamp01/stat/POWER"
  command_topic: "be3/tre/lamp01/cmnd/POWER"
  availability_topic: "be3/tre/lamp01/tele/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

