- platform: travisci
  api_key: !secret travis_api_key
  repository:
  - puzzle/home-assistant-config
  entity_namespace: travis
- platform: mqtt
  name: sonoff-1688
  state_topic: "be3/tux/projector/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"

